# Generated by Django 4.1.6 on 2023-06-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FiftyFriends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('helado', models.TextField()),
            ],
        ),
    ]
